### ISSUE TITLE
Support sending raw transactions via the GSN provider

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-gsn-provider#32]
Support sending raw transactions via the GSN provider. We probably need to catch `eth_sendRawTransaction` besides `eth_sendTransaction`.

Requested by the CryptoManiacs team. Make sure to reach out to them after this issue is closed.

**Comment by shahafn** [comment]
We're still waiting for their reply after Dror's comment. It just doesn't make sense and we're trying to figure out what they are trying to do with `eth_sendRawTransaction`.

**Comment by drortirosh** [comment]
> We may however want to catch `eth_sendRawTransaction` and error out if `_withGSN` is true, since this is probably a developer error.

error flagging seems the right way to go. Using sendSigned/sendRaw probably means a user that didn't understand the system..

**Comment by k06a** [comment]
@nventuro yep we just deserialize tx from `eth_sendRawtransaction` to put it into `eth_sentTrasnsaction` flow, which is working. But it seems you could handle signed transaction more gently.

**Comment by k06a** [comment]
@nventuro yep we just deserialize tx from `eth_sendRawtransaction` to put it into `eth_sentTrasnsaction` flow, which is working. But it seems you could handle signed transaction more gently.

**Comment by drortirosh** [comment]
it is much better to reject this transaction (so the user knows he signed the wrong thing, and has to figure out how to do sendTransaction with the correct credentials and "from" field,)
Silently trying to "fix" the mistake and handle this transaction can lead to unexpected results: wrong `from` field, strange gas usage, `value` ignored, etc

**Comment by k06a** [comment]
@drortirosh what do you mean "he signed the wrong thing"? You not got what I am talking about. Clients of your library - developers can decide to sign transaction on their own. You can get this signed transaction and forward to your nodes only. Whom from what are you going to protect?

**Comment by k06a** [comment]
Your usual flow:
1. Web3 submits unsigned Tx
2. GSN provider gets Tx and forwards it to original provider for signing
3. Users signs Tx with MetaMask or other wallet
4. GSN provider forwards signed Tx to GSN nodes

**Comment by nventuro** [comment]
@k06a I believe what @drortirosh is trying to convey is that what the user signs when using the GSN is not an Ethereum transaction, but a _relay request_, which are slightly different. Among those differences, the address of the relayer is one of the signed values, hence the need for the provider to receive the raw values, and only ask the user for a signature once it has found a working relayer.

The required information (`to`, `data`, `gasPrice, `gasLimit`) can of course be extracted from a signed transaction, discarding value and the signature itself, but this poses two issues:
 1. the user had two sign _two_ values: the discarded Ethereum transaction and the GSN relay request
2. the `value` field of the transaction will be discarded

It's because of these reasons that we think it's better to raise an error when an attempt to perform a relay request with already signed data is made.

**Comment by k06a** [comment]
@nventuro got it, that's makes sense.
