### ISSUE TITLE
List next changes to RelayHub

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-gsn-provider#40]
There are pending changes to the RelayHub. List them here so we can coordinate work to upgrade it.

**Comment by nventuro** [comment]
This is simply a compilation of requests. I don't necessarily agree with all of them, and am not sure what the value added is for some of them.

1. Allow for parameters (e.g. minimum stake, delays) to change without a redeploy (somehow)
1. Make parameters configurable, so that they don't have to be the same in all networks
1. Overhaul events, specially those emitted on first register vs. keep alive (related to https://github.com/tabookey/tabookey-gasless/issues/179)
1. Store relayer data (e.g. url) on storage instead of emitting it on events
1. Split into modules stored at different addresses, to make upgrades less disruptive (e.g. have the penalization and relayer registration mechanisms in separate contracts)
1. Rework gas limits on `accept`, `pre` and `post`. Consensus seems to be that freedom should be given to either the users or recipients to choose this limit for themselves (see https://github.com/tabookey/tabookey-gasless/issues/234)
1. Prevent users from spamming relayers with relay-requests, causing their transactions to revert. @Austin-Williams had some interesting ideas on this front along the lines of forcing the relayers to cooperate and detect these spammers, but those create some issues of their own. 
1. Provider a clearer upgrade mechanism for recipients. `RelayHub` or some other contract might indicate the current hub has been deprecated and point to a newer version (who controls this?)

Many of these changes (configurable parameters, multiple contracts) make it impossible to keep using Nick's method to get a unique address in all networks, but we can still achieve this with contract factories that rely on `create2`.

**Comment by drortirosh** [comment]
I suggest we create separate issue for each such new feature, and tag then as GsnNext. This way we can discuss each feature separately.

**Comment by spalladino** [comment]
@drortirosh I clustered them into 3 main topics (upgrades, events, and gas limits) and listed them [here](https://github.com/tabookey/tabookey-gasless/issues/247), along with links to the specific issues. 

I'll close this issue in favour of the one in the tabookey repo, where the RelayHub code is.
